### ISSUE TITLE
sha256 mismatch on gem v0.4.8

### ISSUE THREAD

**Issue by bleything** [ninech/netbox-client-ruby#27]
According to [rubygems.org](https://rubygems.org/gems/netbox-client-ruby/versions/0.4.8) the SHA-256 sum of v0.4.8 should be `923da7747009e3bbb8acc37b56dca3e1b7e86720929ec9d000d32f37db82a475`. But when I download the file:

```
$ curl -sLO https://rubygems.org/downloads/netbox-client-ruby-0.4.8.gem
$ shasum -a 256 netbox-client-ruby-0.4.8.gem
7369d19d40d39d060abe413bfa026170f94403a8c2c31d97dea077bba3b84108  netbox-client-ruby-0.4.8.gem
```

This is relevant because bundler will refuse to install the gem if the SHA-256 doesn't match.

I did some digging and turned up rubygems/rubygems.org#1551, and in particular [this comment](https://github.com/rubygems/rubygems.org/issues/1551#issuecomment-290924620) which discusses causes and potential resolutions.

It seems like the only solution right now is to release a new version :/

**Comment by cimnine** [comment]
Thank you for raising this issue and researching solutions.
