### ISSUE TITLE
locked down dependencies

### ISSUE THREAD

**Issue by darix** [ninech/netbox-client-ruby#32]
e.g. for faraday it could allow newer versions or is there anything that blocks that?

**Comment by darix** [comment]
basic testing makes me think the new faraday option would just work

**Comment by cimnine** [comment]
I seem to remember that there was an issue with some version of faraday.
Unfortunately I don't work for the organization ninech anymore, and I believe they don't actively use this gem anymore.

**Comment by thde** [comment]
I'm happy to review and merge if you find time for a PR.

**Comment by thde** [comment]
I think this should fix it:
https://github.com/ninech/netbox-client-ruby/releases/tag/0.5.3
