### ISSUE TITLE
.json suffix on API requests no longer works (netbox 4).

### ISSUE THREAD

**Issue by jaark** [ninech/netbox-client-ruby#89]
I have just updated to Netbox 4.1 (from 3.something) and this gem no longer works when trying to request individual records.

For example, 
`NetboxClientRuby.dcim.interface(1).get!`

Results in a 500 error with the following exception detail from Netbox :

> 
> **<class 'django.core.exceptions.ImproperlyConfigured'>**
> 
> Could not resolve URL for hyperlinked relationship using view name "". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

I noticed that the get request generated from the gem is

http://netbox.server/api/dcim/interfaces/1.json

However, the API functions correctly if the request is

http://netbox.server/api/dcim/interfaces/1

The same pattern occurs for other objects I have tried (e.g. devices etc.)

It looks like I would be able to fix this by modifying the 'path' line in each entity class and removing the '.json', however this is the very first time I have looked at the netbox-client-ruby code and I am unsure if this would have an effect for those still running older versions of netbox -- can anyone advise please?

**Comment by thde** [comment]
> It looks like I would be able to fix this by modifying the 'path' line in each entity class and removing the '.json', however this is the very first time I have looked at the netbox-client-ruby code and I am unsure if this would have an effect for those still running older versions of netbox -- can anyone advise please?

Based on https://github.com/netbox-community/netbox/issues/17610#issuecomment-2377003501 it is possible that including the suffic was wrong all along. Otherwise I'm also happy no note that a newer version of Netbox is required tbh. So if you want to make a MR, I'm happy to have a look at it.
